[[manager.prepend_keymap]]
on   = [ "m", "c" ]
run  = "plugin vcs-files"
desc = "Show Git file changes"

[[manager.prepend_keymap]]
on   = [ "c", "m" ]
run  = "plugin chmod"
desc = "Chmod on selected files"
